const GREENHOUSE_URL = "https://canonical.greenhouse.io";
const AUTH_URL = "https://login.ubuntu.com";
const COPY_FROM_BOARD = "Canonical";
const COPY_TO_BOARD = "Canonical - Jobs";
const TEST_JOB_BOARD = "Test Board";
const PROTECTED_JOB_BOARDS = ["Canonical", "Internal"];
const USER_SETTINGS_FILE = "canonical-greenhouse.json";
const FILTERED_ATTRIBUTES = [
    "location_questions",
    "metadata",
    "requisition_id",
    "silo_id",
    "same_content",
    "update_at",
    "created_at",
    "fingerprint",
    "id",
    "first_published",
    "offices",
    "post_type",
    "post_under",
    "prospect_post",
    "public_url",
    "post_type",
    "all_department_ids",
    "all_office_ids",
    "office_ids",
    "questions_for_api",
    "compliance",
    "data_compliance",
    "departments",
    "free_job_board_location",
    "greenhouse_job_board_id",
    "iframe_height",
    "job_board_partner_ids",
    "job_board_updated_at",
    "education",
    "live",
    "location",
    "updated_at",
];

// Regions and cities

export const usaCities: string[] = [
    "Home based - Americas, Atlanta",
    "Home based - Americas, Anchorage",
    "Home based - Americas, Austin",
    "Home based - Americas, Baltimore",
    "Home based - Americas, Boise",
    "Home based - Americas, Boston",
    "Home based - Americas, Buffalo",
    "Home based - Americas, Charlotte",
    "Home based - Americas, Chicago",
    "Home based - Americas, Cincinnati",
    "Home based - Americas, Cleveland",
    "Home based - Americas, Columbus",
    "Home based - Americas, Dallas",
    "Home based - Americas, Dayton",
    "Home based - Americas, Albany",
    "Home based - Americas, Detroit",
    "Home based - Americas, Fresno",
    "Home based - Americas, Honolulu",
    "Home based - Americas, Houston",
    "Home based - Americas, Jacksonville, Florida",
    "Home based - Americas, Kansas City",
    "Home based - Americas, Las Vegas",
    "Home based - Americas, Los Angeles",
    "Home based - Americas, Madison",
    "Home based - Americas, Miami",
    "Home based - Americas, Milwaukee",
    "Home based - Americas, Minneapolis",
    "Home based - Americas, Nashville, Tennessee",
    "Home based - Americas, New York",
    "Home based - Americas, Omaha",
    "Home based - Americas, Oklahoma City",
    "Home based - Americas, Philadelphia",
    "Home based - Americas, Phoenix",
    "Home based - Americas, Pittsburgh",
    "Home based - Americas, Portland",
    "Home based - Americas, Raleigh",
    "Home based - Americas, Rochester",
    "Home based - Americas, Sacramento",
    "Home based - Americas, San Antonio, Texas",
    "Home based - Americas, San Diego",
    "Home based - Americas, San Bernardino, California, United States",
    "Home based - Americas, San Francisco",
    "Home based - Americas, San Jose, California",
    "Home based - Americas, Salt Lake City",
    "Home based - Americas, Seattle",
    "Home based - Americas, Spokane, Washington",
    "Home based - Americas, Syracuse",
    "Home based - Americas, Tacoma",
    "Home based - Americas, Tucson",
    "Home based - Americas, Tulsa",
    "Home based - Americas, Washington",
    "Home based - Americas, Wichita",
];
const canadaCities: string[] = [
    "Home based - Canada, Calgary",
    "Home based - Canada, Montreal",
    "Home based - Canada, Laval",
    "Home based - Canada, Sherbrooke",
    "Home based - Canada, Trois-Rivieres",
    "Home based - Canada, Gatineau",
    "Home based - Canada, Ottawa",
    "Home based - Canada, Toronto",
    "Home based - Canada, Mississauga",
    "Home based - Canada, Hamilton",
    "Home based - Canada, Sudbury",
    "Home based - Canada, Moncton",
    "Home based - Canada, Winnipeg",
    "Home based - Canada, Regina",
    "Home based - Canada, Edmonton",
    "Home based - Canada, Calgary",
    "Home based - Canada, Saint John",
    "Home based - Canada, St. John's",
    "Home based - Canada, Vancouver",
    "Home based - Canada, Victoria, British Columbia",
    "Home based - Canada, Waterloo, Ontario",
];
const latamCities: string[] = [
    "Home based - Latin America, Belo Horizonte",
    "Home based - Latin America, Buenos Aires",
    "Home based - Latin America, Bogota",
    "Home based - Latin America, Caracas",
    "Home based - Latin America, Córdoba",
    "Home based - Latin America, Curitiba",
    "Home based - Latin America, Florianópolis",
    "Home based - Latin America, Guadalajara",
    "Home based - Latin America, Lima",
    "Home based - Latin America, Manaus",
    "Home based - Latin America, Monterrey",
    "Home based - Latin America, Montevideo",
    "Home based - Latin America, Mexico City",
    "Home based - Latin America, Panama City, Panamá, Panama",
    "Home based - Latin America, Porto Alegre",
    "Home based - Latin America, Rio de Janeiro",
    "Home based - Latin America, San José, San José, Costa Rica",
    "Home based - Latin America, Santiago",
    "Home based - Latin America, São Paulo",
];

const REGIONS = {
    americas: [...usaCities, ...canadaCities, ...latamCities],
    canada: [...canadaCities],
    latam: [...latamCities],
    emea: [
        "Home based - Africa, Accra",
        "Home based - Africa, Cairo",
        "Home based - Africa, Cape Town",
        "Home based - Africa, Lagos",
        "Home based - Africa, Nairobi",
        "Home based - Europe, Amsterdam",
        "Home based - Europe, Ankara",
        "Home based - Europe, Antwerp",
        "Home based - Europe, Athens, Attica, Greece",
        "Home based - Europe, Aveiro",
        "Home based - Europe, Barcelona",
        "Home based - Europe, Berlin",
        "Home based - Europe, Bordeaux",
        "Home based - Europe, Bratislava",
        "Home based - Europe, Brno",
        "Home based - Europe, Brussels",
        "Home based - Europe, Bucharest",
        "Home based - Europe, Budapest",
        "Home based - Europe, Cluj-Napoca",
        "Home based - Europe, Coimbra",
        "Home based - Europe, Dresden",
        "Home based - Europe, Dublin",
        "Home based - Europe, Dusseldorf",
        "Home based - Europe, Edinburgh",
        "Home based - Europe, Frankfurt",
        "Home based - Europe, Glasgow",
        "Home based - Europe, Granada",
        "Home based - Europe, Grenoble",
        "Home based - Europe, Hamburg",
        "Home based - Europe, Helsinki",
        "Home based - Europe, Istanbul",
        "Home based - Europe, Kraków",
        "Home based - Europe, Leipzig",
        "Home based - Europe, Lille",
        "Home based - Europe, Lisbon",
        "Home based - Europe, Ljubljana",
        "Home based - Europe, London",
        "Home based - Europe, Lyon",
        "Home based - Europe, Madrid",
        "Home based - Europe, Malaga",
        "Home based - Europe, Manchester",
        "Home based - Europe, Marousi",
        "Home based - Europe, Marseille",
        "Home based - Europe, Metz",
        "Home based - Europe, Milan",
        "Home based - Europe, Munich",
        "Home based - Europe, Murcia",
        "Home based - Europe, Nantes",
        "Home based - Europe, Nice",
        "Home based - Europe, Nuremberg",
        "Home based - Europe, Oslo",
        "Home based - Europe, Paris",
        "Home based - Europe, Pisa",
        "Home based - Europe, Plovdiv",
        "Home based - Europe, Porto, Porto, Portugal",
        "Home based - Europe, Prague",
        "Home based - Europe, Rennes",
        "Home based - Europe, Riga",
        "Home based - Europe, Rome",
        "Home based - Europe, Rotterdam",
        "Home based - Europe, Salamanca",
        "Home based - Europe, Sevilla",
        "Home based - Europe, Sofia",
        "Home based - Europe, Stockholm",
        "Home based - Europe, Strasbourg",
        "Home based - Europe, Tallinn",
        "Home based - Europe, Tartu",
        "Home based - Europe, Timișoara",
        "Home based - Europe, Torino, Turin",
        "Home based - Europe, Toulouse",
        "Home based - Europe, Valencia",
        "Home based - Europe, Vienna",
        "Home based - Europe, Vilnius",
        "Home based - Europe, Warsaw",
        "Home based - Europe, Wrocław",
        "Home based - Europe, Zagreb",
        "Home based - Middle East, Dubai",
        "Home based - Middle East, Doha, Qatar",
        "Home based - Middle East, Manama, Bahrain",
        "Home based - Middle East, Kuwait City, Kuwait",
        "Home based - Middle East, Jeddah, Saudi Arabia",
        "Home based - Middle East, Riyadh, Saudi Arabia",
        "Home based - Middle East, Muscat, Oman",
        "Home based - Middle East, Beirut, Lebanon",
        "Home based - Middle East, Cairo, Egypt",
    ],
    apac: [
        "Home based - Asia Pacific, Adelaide",
        "Home based - Asia Pacific, Auckland",
        "Home based - Asia Pacific, Bangalore",
        "Home based - Asia Pacific, Beijing",
        "Home based - Asia Pacific, Brisbane",
        "Home based - Asia Pacific, Canberra",
        "Home based - Asia Pacific, Chennai",
        "Home based - Asia Pacific, Chengdu",
        "Home based - Asia Pacific, Christchurch",
        "Home based - Asia Pacific, Delhi",
        "Home based - Asia Pacific, Fukuoka",
        "Home based - Asia Pacific, Gurgaon",
        "Home based - Asia Pacific, Hangzhou",
        "Home based - Asia Pacific, Hsinchu",
        "Home based - Asia Pacific, Hong Kong",
        "Home based - Asia Pacific, Hyderabad",
        "Home based - Asia Pacific, Kyoto",
        "Home based - Asia Pacific, Melbourne",
        "Home based - Asia Pacific, Mumbai",
        "Home based - Asia Pacific, Nagoya",
        "Home based - Asia Pacific, Nanjing, Jiangsu",
        "Home based - Asia Pacific, Perth",
        "Home based - Asia Pacific, Pune",
        "Home based - Asia Pacific, Seoul",
        "Home based - Asia Pacific, Shanghai",
        "Home based - Asia Pacific, Shenzhen, Guangdong",
        "Home based - Asia Pacific, Singapore",
        "Home based - Asia Pacific, Sydney",
        "Home based - Asia Pacific, Taipei",
        "Home based - Asia Pacific, Tokyo",
        "Home based - Asia Pacific, Wellington",
        "Home based - Asia Pacific, Wuhan",
        "Home based - Asia Pacific, Xiamen",
    ],
};

export default {
    greenhouseUrl: GREENHOUSE_URL,
    authUrl: AUTH_URL,
    copyFromBoard: COPY_FROM_BOARD,
    copyToBoard: COPY_TO_BOARD,
    testJobBoard: TEST_JOB_BOARD,
    protectedBoards: PROTECTED_JOB_BOARDS,
    userSettingsFile: USER_SETTINGS_FILE,
    filteredAttributes: FILTERED_ATTRIBUTES,
    regions: REGIONS,
};
