name: ght
version: "1.8.1"
summary: Perform actions in Canonical's Greenhouse automatically.
description: An automated browser that does a set of tasks on Canonical's Greenhouse dashboard without the need of interaction with the UI.
base: core22
confinement: strict
grade: stable
architectures:
    - build-on: amd64
    - build-on: arm64
parts:
    node:
        plugin: dump
        source:
            - on amd64: https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-x64.tar.gz
            - on arm64: https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-arm64.tar.gz
        stage:
            - bin
            - include
            - lib
    ght:
        after: [node]
        plugin: nil
        source: .
        build-snaps:
            - chromium
        build-environment:
            - PUPPETEER_SKIP_DOWNLOAD: "true"
            - PUPPETEER_EXECUTABLE_PATH: /snap/chromium/current/bin/chromium.launcher
        override-build: |
            npm install -g yarn
            yarn install
            yarn build
            # this causes PROT_EXEC problem
            rm -f ./node_modules/puppeteer/.local-chromium/linux-*/chrome-linux/nacl_irt_*.nexe
            cp -a ./dist/. $SNAPCRAFT_PART_INSTALL/
            cp -r ./node_modules $SNAPCRAFT_PART_INSTALL
            # Chromium adds this smylink to the root system
            rm $SNAPCRAFT_PART_INSTALL/usr/bin/xdg-email
            # chromium also sets the permissions to use suid for user execution (r-sr-xr-x), this simplifies the permission (r-xr-xr-x)
            chmod 555 $SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser/chrome-sandbox
        stage-snaps:
            - chromium
        stage-packages:
            # dependencies required by chromium
            - libasound2
            - libatk-bridge2.0-0
            - libatk1.0-0
            - libatspi2.0-0
            - libcairo2
            - libcups2
            - libdrm2
            - libgbm1
            - libnss3
            - libpango-1.0-0
            - libx11-6
            - libxau6
            - libxcb1
            - libxcomposite1
            - libxdamage1
            - libxdmcp6
            - libxext6
            - libxfixes3
            - libxkbcommon-x11-0
            - libxrandr2
apps:
    ght:
        command: ght
        environment:
            PUPPETEER_EXECUTABLE_PATH: $SNAP/bin/chromium.launcher
        plugs:
            - desktop
            - desktop-legacy
            - home
            - mount-observe
            - network
            - network-bind
            - opengl
            - unity7
            - x11
