name: ght
version: "1.5.7"
summary: Perform actions in Canonical's Greenhouse automatically.
description: An automated browser that does a set of tasks on Canonical's Greenhouse dashboard without the need of interaction with the UI.
base: core20
confinement: strict
grade: stable
architectures:
    - amd64
    - arm64
parts:
    node:
        plugin: dump
        source:
            - on amd64: https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-x64.tar.xz
            - on arm64: https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-arm64.tar.xz
        stage:
            - bin
            - include
            - lib
    ght:
        after: [node]
        plugin: nil
        source: .
        build-packages:
            - on arm64: ["chromium-browser"]
        override-build: |
            npm config set unsafe-perm true
            npm install -g yarn
            yarn install
            yarn build
            # this causes PROT_EXEC problem
            rm -f ./node_modules/puppeteer/.local-chromium/linux-*/chrome-linux/nacl_irt_*.nexe
            cp -a ./dist/. $SNAPCRAFT_PART_INSTALL/
            cp -r ./node_modules $SNAPCRAFT_PART_INSTALL
        stage-packages:
            # dependencies required by chromium
            - libasound2
            - libatk-bridge2.0-0
            - libatk1.0-0
            - libatspi2.0-0
            - libcairo2
            - libcups2
            - libdrm2
            - libgbm1
            - libnss3
            - libpango-1.0-0
            - libx11-6
            - libxau6
            - libxcb1
            - libxcomposite1
            - libxdamage1
            - libxdmcp6
            - libxext6
            - libxfixes3
            - libxkbcommon-x11-0
            - libxrandr2
apps:
    ght:
        command: ght
        plugs:
            - desktop
            - desktop-legacy
            - home
            - mount-observe
            - network
            - network-bind
            - opengl
            - unity7
            - x11
