import { homedir } from "os";
import { join } from "path";

export const CONFIG_PATH = join(homedir(), ".canonical-greenhouse.json");
export const MAIN_URL = "https://canonical.greenhouse.io/";
export const SSO_DOMAIN = "login.ubuntu.com";
export const SSO_URL = "https://login.ubuntu.com";
export const JOB_BOARD = "Canonical - Jobs";

// remove unnecessary fields that could introduce
// unwanted behavior from the new job post
export const FILTERED_ATTRIBUTES = [
    "location_questions",
    "metadata",
    "requisition_id",
    "silo_id",
    "same_content",
    "update_at",
    "created_at",
    "fingerprint",
    "id",
    "first_published",
    "offices",
    "post_type",
    "post_under",
    "prospect_post",
    "public_url",
    "post_type",
    "all_department_ids",
    "all_office_ids",
    "office_ids",
    "questions_for_api",
    "resume_required",
    "compliance",
    "data_compliance",
    "departments",
    "free_job_board_location",
    "greenhouse_job_board_id",
    "iframe_height",
    "job_board_partner_ids",
    "job_board_updated_at",
    "education",
    "live",
    "location",
    "updated_at",
];

export const PROTECTED_JOB_BOARDS = ["Canonical", "Internal"];

export const REGIONS: { [key: string]: string[] } = {
    americas: [
        "Home based - Americas, Albany",
        "Home based - Americas, Anchorage",
        "Home based - Americas, Atlanta",
        "Home based - Americas, Austin",
        "Home based - Americas, Baltimore",
        "Home based - Americas, Boston",
        "Home based - Americas, Buffalo",
        "Home based - Americas, Charlotte",
        "Home based - Americas, Chicago",
        "Home based - Americas, Cincinnati",
        "Home based - Americas, Cleveland",
        "Home based - Americas, Dallas",
        "Home based - Americas, Dayton",
        "Home based - Americas, Detroit",
        "Home based - Americas, Honolulu",
        "Home based - Americas, Houston",
        "Home based - Americas, Kansas City",
        "Home based - Americas, Los Angeles",
        "Home based - Americas, Madison",
        "Home based - Americas, Miami",
        "Home based - Americas, Milwaukee",
        "Home based - Americas, Minneapolis",
        "Home based - Americas, New York",
        "Home based - Americas, Oklahoma City",
        "Home based - Americas, Omaha",
        "Home based - Americas, Philadelphia",
        "Home based - Americas, Phoenix",
        "Home based - Americas, Pittsburgh",
        "Home based - Americas, Portland",
        "Home based - Americas, Raleigh",
        "Home based - Americas, Rochester",
        "Home based - Americas, Sacramento",
        "Home based - Americas, San Diego",
        "Home based - Americas, San Francisco",
        "Home based - Americas, Salt Lake City",
        "Home based - Americas, Seattle",
        "Home based - Americas, Tulsa",
        "Home based - Americas, Wichita",
        "Home based - Americas, Washington",
        "Home based - Americas, Calgary",
        "Home based - Americas, Montreal",
        "Home based - Americas, Ottawa",
        "Home based - Americas, Toronto",
        "Home based - Americas, Vancouver",
        "Home based - Americas, Belo Horizonte",
        "Home based - Americas, Buenos Aires",
        "Home based - Americas, Bogota",
        "Home based - Americas, Caracas",
        "Home based - Americas, Córdoba",
        "Home based - Americas, Curitiba",
        "Home based - Americas, Florianópolis",
        "Home based - Americas, Guadalajara",
        "Home based - Americas, Lima",
        "Home based - Americas, Manaus",
        "Home based - Americas, Monterrey",
        "Home based - Americas, Mexico City",
        "Home based - Americas, Porto Alegre",
        "Home based - Americas, Rio de Janeiro",
        "Home based - Americas, Santiago",
        "Home based - Americas, São Paulo",
    ],
    emea: [
        "Home based - Africa, Accra",
        "Home based - Africa, Cairo",
        "Home based - Africa, Cape Town",
        "Home based - Africa, Lagos",
        "Home based - Africa, Nairobi",
        "Home based - Europe, Amsterdam",
        "Home based - Europe, Ankara",
        "Home based - Europe, Barcelona",
        "Home based - Europe, Berlin",
        "Home based - Europe, Bratislava",
        "Home based - Europe, Brno",
        "Home based - Europe, Brussels",
        "Home based - Europe, Bucharest",
        "Home based - Europe, Budapest",
        "Home based - Europe, Cluj-Napoca",
        "Home based - Europe, Dublin",
        "Home based - Europe, Edinburgh",
        "Home based - Europe, Frankfurt",
        "Home based - Europe, Glasgow",
        "Home based - Europe, Helsinki",
        "Home based - Europe, Istanbul",
        "Home based - Europe, Kraków",
        "Home based - Europe, Lisbon",
        "Home based - Europe, Ljubljana",
        "Home based - Europe, London",
        "Home based - Europe, Lyon",
        "Home based - Europe, Madrid",
        "Home based - Europe, Manchester",
        "Home based - Europe, Marousi",
        "Home based - Europe, Milan",
        "Home based - Europe, Moscow",
        "Home based - Europe, Munich",
        "Home based - Europe, Oslo",
        "Home based - Europe, Paris",
        "Home based - Europe, Plovdiv",
        "Home based - Europe, Prague",
        "Home based - Europe, Riga",
        "Home based - Europe, Rome",
        "Home based - Europe, Sofia",
        "Home based - Europe, St. Petersburg",
        "Home based - Europe, Stockholm",
        "Home based - Europe, Tallinn",
        "Home based - Europe, Timișoara",
        "Home based - Europe, Vienna",
        "Home based - Europe, Vilnius",
        "Home based - Europe, Warsaw",
        "Home based - Europe, Wrocław",
        "Home based - Europe, Zagreb",
    ],
    apac: [
        "Home based - Asia Pacific, Auckland",
        "Home based - Asia Pacific, Bangalore",
        "Home based - Asia Pacific, Beijing",
        "Home based - Asia Pacific, Brisbane",
        "Home based - Asia Pacific, Chennai",
        "Home based - Asia Pacific, Christchurch",
        "Home based - Asia Pacific, Delhi",
        "Home based - Asia Pacific, Gurgaon",
        "Home based - Asia Pacific, Hangzhou",
        "Home based - Asia Pacific, Hsinchu",
        "Home based - Asia Pacific, Hong Kong",
        "Home based - Asia Pacific, Hyderabad",
        "Home based - Asia Pacific, Melbourne",
        "Home based - Asia Pacific, Mumbai",
        "Home based - Asia Pacific, Pune",
        "Home based - Asia Pacific, Seoul",
        "Home based - Asia Pacific, Shanghai",
        "Home based - Asia Pacific, Singapore",
        "Home based - Asia Pacific, Sydney",
        "Home based - Asia Pacific, Taipei",
        "Home based - Asia Pacific, Tokyo",
        "Home based - Asia Pacific, Wellington",
    ],
};
