export const usaCities: string[] = [
    "Home based - Americas, Atlanta",
    "Home based - Americas, Anchorage",
    "Home based - Americas, Austin",
    "Home based - Americas, Baltimore",
    "Home based - Americas, Boise",
    "Home based - Americas, Boston",
    "Home based - Americas, Buffalo",
    "Home based - Americas, Charlotte",
    "Home based - Americas, Chicago",
    "Home based - Americas, Cincinnati",
    "Home based - Americas, Cleveland",
    "Home based - Americas, Columbus",
    "Home based - Americas, Dallas",
    "Home based - Americas, Dayton",
    "Home based - Americas, Albany",
    "Home based - Americas, Detroit",
    "Home based - Americas, Fresno",
    "Home based - Americas, Honolulu",
    "Home based - Americas, Houston",
    "Home based - Americas, Jacksonville, Florida",
    "Home based - Americas, Kansas City",
    "Home based - Americas, Las Vegas",
    "Home based - Americas, Los Angeles",
    "Home based - Americas, Madison",
    "Home based - Americas, Miami",
    "Home based - Americas, Milwaukee",
    "Home based - Americas, Minneapolis",
    "Home based - Americas, Nashville, Tennessee",
    "Home based - Americas, New York",
    "Home based - Americas, Omaha",
    "Home based - Americas, Oklahoma City",
    "Home based - Americas, Philadelphia",
    "Home based - Americas, Phoenix",
    "Home based - Americas, Pittsburgh",
    "Home based - Americas, Portland",
    "Home based - Americas, Raleigh",
    "Home based - Americas, Rochester",
    "Home based - Americas, Sacramento",
    "Home based - Americas, San Antonio, Texas",
    "Home based - Americas, San Diego",
    "Home based - Americas, San Bernardino, California, United States",
    "Home based - Americas, San Francisco",
    "Home based - Americas, San Jose, California",
    "Home based - Americas, Salt Lake City",
    "Home based - Americas, Seattle",
    "Home based - Americas, Spokane, Washington",
    "Home based - Americas, Syracuse",
    "Home based - Americas, Tacoma",
    "Home based - Americas, Tucson",
    "Home based - Americas, Tulsa",
    "Home based - Americas, Washington",
    "Home based - Americas, Wichita",
];

export const regions: { [key: string]: string[] } = {
    americas: [
        ...usaCities,
        "Home based - Americas, Calgary",
        "Home based - Americas, Montreal",
        "Home based - Americas, Ottawa",
        "Home based - Americas, Toronto",
        "Home based - Americas, Vancouver",
        "Home based - Americas, Victoria, British Columbia",
        "Home based - Americas, Belo Horizonte",
        "Home based - Americas, Buenos Aires",
        "Home based - Americas, Bogota",
        "Home based - Americas, Caracas",
        "Home based - Americas, Córdoba",
        "Home based - Americas, Curitiba",
        "Home based - Americas, Florianópolis",
        "Home based - Americas, Guadalajara",
        "Home based - Americas, Lima",
        "Home based - Americas, Manaus",
        "Home based - Americas, Monterrey",
        "Home based - Americas, Montevideo",
        "Home based - Americas, Mexico City",
        "Home based - Americas, Panama City, Panamá, Panama",
        "Home based - Americas, Porto Alegre",
        "Home based - Americas, Rio de Janeiro",
        "Home based - Americas, San José, San José, Costa Rica",
        "Home based - Americas, Santiago",
        "Home based - Americas, São Paulo",
        "Home based - Americas, Waterloo Ontario",
    ],
    emea: [
        "Home based - Africa, Accra",
        "Home based - Africa, Cairo",
        "Home based - Africa, Cape Town",
        "Home based - Africa, Lagos",
        "Home based - Africa, Nairobi",
        "Home based - Europe, Amsterdam",
        "Home based - Europe, Ankara",
        "Home based - Europe, Athens, Attica, Greece",
        "Home based - Europe, Barcelona",
        "Home based - Europe, Berlin",
        "Home based - Europe, Bratislava",
        "Home based - Europe, Brno",
        "Home based - Europe, Brussels",
        "Home based - Europe, Bucharest",
        "Home based - Europe, Budapest",
        "Home based - Europe, Cluj-Napoca",
        "Home based - Europe, Dublin",
        "Home based - Europe, Edinburgh",
        "Home based - Europe, Frankfurt",
        "Home based - Europe, Glasgow",
        "Home based - Europe, Helsinki",
        "Home based - Europe, Istanbul",
        "Home based - Europe, Kraków",
        "Home based - Europe, Lisbon",
        "Home based - Europe, Ljubljana",
        "Home based - Europe, London",
        "Home based - Europe, Lyon",
        "Home based - Europe, Madrid",
        "Home based - Europe, Manchester",
        "Home based - Europe, Marousi",
        "Home based - Europe, Milan",
        "Home based - Europe, Moscow",
        "Home based - Europe, Munich",
        "Home based - Europe, Oslo",
        "Home based - Europe, Paris",
        "Home based - Europe, Plovdiv",
        "Home based - Europe, Prague",
        "Home based - Europe, Riga",
        "Home based - Europe, Rome",
        "Home based - Europe, Sofia",
        "Home based - Europe, St. Petersburg",
        "Home based - Europe, Stockholm",
        "Home based - Europe, Tallinn",
        "Home based - Europe, Timișoara",
        "Home based - Europe, Vienna",
        "Home based - Europe, Vilnius",
        "Home based - Europe, Warsaw",
        "Home based - Europe, Wrocław",
        "Home based - Europe, Zagreb",
        "Home based - Europe, Malaga",
        "Home based - Europe, Valencia",
        "Home based - Europe, Tartu",
    ],
    apac: [
        "Home based - Asia Pacific, Adelaide",
        "Home based - Asia Pacific, Auckland",
        "Home based - Asia Pacific, Bangalore",
        "Home based - Asia Pacific, Beijing",
        "Home based - Asia Pacific, Brisbane",
        "Home based - Asia Pacific, Canberra",
        "Home based - Asia Pacific, Chennai",
        "Home based - Asia Pacific, Chengdu",
        "Home based - Asia Pacific, Christchurch",
        "Home based - Asia Pacific, Delhi",
        "Home based - Asia Pacific, Gurgaon",
        "Home based - Asia Pacific, Hangzhou",
        "Home based - Asia Pacific, Hsinchu",
        "Home based - Asia Pacific, Hong Kong",
        "Home based - Asia Pacific, Hyderabad",
        "Home based - Asia Pacific, Melbourne",
        "Home based - Asia Pacific, Mumbai",
        "Home based - Asia Pacific, Nanjing, Jiangsu",
        "Home based - Asia Pacific, Perth",
        "Home based - Asia Pacific, Pune",
        "Home based - Asia Pacific, Seoul",
        "Home based - Asia Pacific, Shanghai",
        "Home based - Asia Pacific, Shenzhen, Guangdong",
        "Home based - Asia Pacific, Singapore",
        "Home based - Asia Pacific, Sydney",
        "Home based - Asia Pacific, Taipei",
        "Home based - Asia Pacific, Tokyo",
        "Home based - Asia Pacific, Wellington",
        "Home based - Asia Pacific, Wuhan",
        "Home based - Asia Pacific, Xiamen",
        "Home based - Asia Pacific, Fukuoka",
        "Home based - Asia Pacific, Kyoto",
        "Home based - Asia Pacific, Nagoya",
        "Home based - Asia Pacific, Osaka",
    ],
};
